version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "admin@123"
    ports:
      - "1433:1433"
    networks:
      - sqlserver-network
    restart: always

networks:
  sqlserver-network:
    driver: bridge
